# Generated by Django 6.0.5 on 2026-05-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('titulo_contenido', models.CharField(max_length=20)),
                ('contenido', models.CharField(max_length=200)),
                ('gmail', models.CharField(max_length=25)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
