# Generated by Django 6.0.5 on 2026-05-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='contenido',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='gmail',
            field=models.EmailField(max_length=30),
        ),
    ]
