# Generated by Django 6.0.5 on 2026-05-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_consultas_contenido_alter_consultas_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='contenido',
            field=models.TextField(max_length=400),
        ),
    ]
