# Generated by Django 6.0.5 on 2026-05-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alter_consultas_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
